//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace msit.twitterScore.Twitter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Twitter : global::System.Configuration.ApplicationSettingsBase {
        
        private static Twitter defaultInstance = ((Twitter)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Twitter())));
        
        public static Twitter Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xZAzBqoImFA8IEiEJtFcli29Z")]
        public string CONSUMER_KEY {
            get {
                return ((string)(this["CONSUMER_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MtE6sefA3N3LBZiF1SUstbOosp3Mwpe2IEPsoZ0A3XrHNj3Wcm")]
        public string CONSUMER_SECRET {
            get {
                return ((string)(this["CONSUMER_SECRET"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1931910810-4rMRPIYlDiCcmAJDz4FV2NdiEFpVoFaSJ062TYl")]
        public string ACCESS_TOKEN {
            get {
                return ((string)(this["ACCESS_TOKEN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eijpOAtyVVj87Qh8Sryh8i5vUZunNkjEBnWlO20GzRAHZ")]
        public string ACCESS_TOKEN_SECRET {
            get {
                return ((string)(this["ACCESS_TOKEN_SECRET"]));
            }
        }
    }
}
